### ISSUE TITLE
Missing code

### ISSUE THREAD

**Issue by cvweiss** [ErikKalkoken/ept#4]
I'd like to implement your trophies into zKillboard, but your code isn't available or open source

**Comment by ErikKalkoken** [comment]
sorry mate, but I have not yet decided if I want to make my code public. But I am happy to share it with you if you are still interested.

**Comment by cvweiss** [comment]
Hey no worries, I ended up writing something from scratch for zkillboard, for example, here is one of the top characters: https://zkillboard.com/character/1941616627/trophies/
